### ISSUE TITLE
Getting syntax error from MySQL

### ISSUE THREAD

**Issue by piyushsutariya** [nielsgl/sequelize-paper-trail#10] opened 2017-02-17 07:11 UTC
I have followed all step which are mention for installing and using in model. when I started my server, I got following error.
_Unhandled rejection SequelizeBaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JSON NOT NULL, `documentId` INTEGER NOT NULL, `revision` INTEGER NOT NULL, `crea' at line 1_

I have solved that issue by just change of JSON to TEXT in following code in index file of package.
_attributes = {
        path: {
          type: Sequelize.TEXT,
          allowNull: false
        },
        document: {
          type: Sequelize.JSON,
          allowNull: false
        },
        diff: {
          type: Sequelize.JSON,
          allowNull: false
        }
      };_
  
But still its giving me other error that is:
Unhandled rejection SequelizeBaseError: ER_DUP_FIELDNAME: Duplicate column name 'RevisionId'

Now I am not able solved this error. Could you please help me for that

**Comment by piyushsutariya** [comment] 2017-02-17 09:45
opened this issue 3 hours ago

**Comment by stephenbeauchamp** [comment] 2017-03-14 11:54
I'm having the same issue, mysql trace shows, revisionId and RevisionId columns in the RevisionChange table:

`Query	CREATE TABLE IF NOT EXISTS `RevisionChange` (`id` INTEGER NOT NULL auto_increment , `path` TEXT NOT NULL, `document` JSON NOT NULL, `diff` JSON NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `revisionId` INTEGER, `RevisionId` INTEGER, PRIMARY KEY (`id`), FOREIGN KEY (`RevisionId`) REFERENCES `Revision` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB`

**Comment by stephenbeauchamp** [comment] 2017-03-15 10:00
The conflicting columns are created by the following lines of code in /lib/index.js

`      // Set associations
      Revision.hasMany(RevisionChange, { // EDIT: Creates revisionId Column
        foreignKey: options.defaultAttributes.revisionId,
        constraints: false
      });

      RevisionChange.belongsTo(Revision); // EDIT: Creates RevisionId Column
`
This is resolved by changing  the last line to:

`RevisionChange.belongsTo(Revision, { foreignKey: options.defaultAttributes.revisionId });`

If you agree that is an appropriate fix, I'm happy to set up a pull request - with better formatting of course? Or would you just prefer to edit the file yourself?

**Comment by nielsgl** [comment] 2017-10-29 11:27
Is this still an issue? PRs are always welcome, closing for now, please reopen if the issue remains.

**Comment by ksfreitas** [comment] 2018-12-27 01:17
This bug exists. I found the cause: MySQL   Windows is case insensitive by default. In source code, in the `RevisionChange` relation with `Revision` model, the foreign field name is defined automatticly in line 436:

`        RevisionChange.belongsTo(Revision);`

The fix should be done with care to not broke existing implementation. @nielsgl can you reopen this ticket?

**Comment by nielsgl** [comment] 2018-12-27 10:02
@ksfreitas thanks for your comment. I plan to review the open PRs in the coming days, feel free to open one to resolve this issue.

**Closed** 2019-03-14 13:39 UTC
Labels: bug

**Comment by EdByrnee** [comment] 2019-05-31 11:43
Did anyone get a working fix for this issue?

**Comment by EdByrnee** [comment] 2019-05-31 11:50
This is caused by 

> This bug exists. I found the cause: MySQL Windows is case insensitive by default. In source code, in the `RevisionChange` relation with `Revision` model, the foreign field name is defined automatically in line 436:
> 
> ` RevisionChange.belongsTo(Revision);`
> 
> The fix should be done with care to not broke existing implementation. @nielsgl can you reopen this ticket?

I got this bug on Ubuntu, I think this is when using mysql less than 8 you cannot have a NOT NULL default value on a json column

**Comment by nielsgl** [comment] 2019-05-31 13:53
@EdByrnee which version of sequelize-paper-trail are you using? If not the latest, can you try it with `sequelize-paper-trail@3.0.0-rc.8` ?

**Comment by imjordanxd** [comment] 2021-05-03 01:05
still an issue

**Comment by erikpols** [comment] 2021-07-10 16:42
same, still an issue.
